[config]
label = "root"

[[config.menu]]
label = "item1"
command = "echo 1"

[[config.menu]]
label = "bad"
command = "eco 2"

[[config.menu]]
label = "sub1"

[[config.menu.submenu]]
label = "item1"
command = "echo 1"

[[config.menu.submenu]]
label = "sub1sub1"

[[config.menu.submenu.submenu]]
label = "item2"
command = "echo 2"

[[config.menu.submenu.submenu]]
label = "item3"
command = "echo 3"

[[config.menu.submenu]]
label = "item4"
command = "echo 4"

[[config.menu]]
label = "sub2"

[[config.menu.submenu]]
label = "item1"
command = "echo 1"

[[config.menu.submenu]]
label = "item2"
command = "echo 1"
