# SPDX-FileCopyrightText: 2025-2026 Jonatan Wincent <jonatan.wincent@proton.me>
# SPDX-License-Identifier: MIT
[config]
label = "Power Menu"

[[config.menu]]
label = "󰜺    Cancel"
command = ""

[[config.menu]]
label = "    Shutdown"
command = "systemctl poweroff"

[[config.menu]]
label = "    Reboot"
command = "systemctl reboot"

[[config.menu]]
label = "󰤄    Suspend"
command = "systemctl suspend"

[[config.menu]]
label = "    Hibernate"
command = "systemctl hibernate"

[[config.menu]]
label = "    Lock"
command = "hyprlock"
